name: JCO Paper Monitor

on:
  schedule:
    # 修改为每小时运行一次 (即每个小时的第 0 分钟触发)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-and-notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python main.py

    - name: Commit and Push History
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add history.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "update history" && git push)
